<h2>Todo List for <?php echo $waiter; ?></h2>

<?php

foreach($result as $key => $table)
{
?>
<h3>Table #<?php echo $key; ?></h3>

<table>
    <tr>
        <th>Menu #</th>
        <th>Description</th>
    </tr>
    <?php
    foreach($table as $liste)
    {
        ?>
    <tr>
        <td><?php echo $liste->getMenuNumber() ;?></td>
        <td><?php echo $liste->getDescription() ; ?></td>
    </tr>
        <?php
    }
    ?>
</table>

<a href='<?php echo $this->url('tab/status', array('id' => $key)) ; ?>'>Voir la commande</a>
<?php
}