<h2>Todo List for <?php echo $waiter; ?></h2>

<?php
foreach($result as $key => $table)
{
?>
<h3>Table #<?php echo $key; ?></h3>
<form action='<?php echo $this->url('staff/markserved') ; ?>' method='post'>
<input type='hidden' name='id' value='<?php echo $key; ?>'/>
<input type='hidden' name='waiter' value='<?php echo $waiter; ?>'/>
<table>
    <tr>
        <th>Menu #</th>
        <th>Description</th>
        <th>Served</th>
    </tr>
    <?php
    foreach($table as $liste)
    {
        ?>
    <tr>
        <td><?php echo $liste->getMenuNumber() ;?></td>
        <td><?php echo $liste->getDescription() ; ?></td>
        <td><input type='checkbox' name='served[]' value='served_<?php echo $liste->getMenuNumber() ; ?>'/></td>
    </tr>
        <?php
    }
    ?>
</table>

<a href='<?php echo $this->url('tab/status', array('id' => $key)) ; ?>'>Voir la commande</a>
<input type='submit' name='submit' value='Mark Served'/>
</form>
<?php
}
