<?php
$tab = $result['status'] ;
$form = $result['form'] ;
$form->prepare() ;
?>

<h3>Encaisser pour la table #<?php echo $tab->getTableNumber() ; ?> </h3>

<table>    
<?php

foreach($tab->getItems() as $item)
{
?>
    <tr>
        <td><?php echo $item->getMenuNumber() ; ?></td>
        <td><?php echo $item->getDescription() ; ?></td>
        <td><?php echo $item->getPrice() ; ?></td>
    </tr>
<?php
}
?>
    <tr>
        <td>Total</td>
        <td></td>
        <td><?php echo $tab->getTotal() ; ?></td>
    </tr>
</table>

<?php

$form->setAttribute('action',  $this->url('tab/close', array('id' => $tab->getTableNumber()))) ;
$form->setAttribute('method', 'post') ;

?>

<?php  echo $this->form()->openTag($form) ; ?>
<div class='form-group'>
<?php  echo $this->formRow($form->get('amountPaid')) ; ?>
</div>
<?php
echo $this->formRow($form->get('security')) ;
echo $this->formHidden($form->get('id')) ;
echo $this->formRow($form->get('submit')) ;

echo $this->form()->closeTag() ;
?>
