<h3>Encaisser pour la table #<?php echo $result->getTableNumber() ; ?> </h3>

<table>    
<?php

foreach($result->getItems() as $item)
{
?>
    <tr>
        <td><?php echo $item->getMenuNumber() ; ?></td>
        <td><?php echo $item->getDescription() ; ?></td>
        <td><?php echo $item->getPrice() ; ?></td>
    </tr>
<?php
}
?>
    <tr>
        <td>Total</td>
        <td></td>
        <td><?php echo $result->getTotal() ; ?></td>
    </tr>
</table>