<h1>Tab status</h1>

<h2>Table #<?php echo $result->getTableNumber(); ?></h2>
<?php

var_dump($result) ;

?>

<div><a href="<?php echo $this->url('tab/order', array('id' => $result->getTableNumber())) ;?>">Order Food/Drink</a></div>

<h3>Items to serve</h3>

<?php
if(count($result->getItemsToServe()) == 0)
{
    echo 'Pas de commande en cours' ;
} else {
?>
<form method='post' action='<?php echo $this->url('tab/markserved') ; ?>'> <!-- mark served action table number-->
<input type='hidden' name='tableNumber' value='<?php echo $result->getTableNumber() ; ?>'/>
    <table>
    <tr>
        <th>Menu #</th>
        <th>Description</th>
        <th>Mark Served</th>
    </tr>
<?php
    $i = 0 ;
    foreach($result->getItemsToServe() as $k=> $v)
    {
        echo "<tr>" ;
        echo "<td>" .$v->getMenuNumber(). "</td>" ;
        echo "<td>" .$v->getDescription() . "</td>" ;
        echo "<td><input type='checkbox' name='served[]' value='menu_" .$i++. "_" .$v->getMenuNumber(). "'/></td>" ;
        echo "</tr>" ;
    }
?>
</table>
    <input type='submit' value='Mark served'/>
</form>
<?php
}
?>


<h3>Food in preparation</h3>

<?php
if(count($result->getItemsInPreparation()) == 0)
{
    echo 'Pas de commande en cours' ;
} else {
?>
<table>
    <tr>
        <th>Menu #</th>
        <th>Description</th>
    </tr>
<?php    
    foreach($result->getItemsInPreparation() as $k=> $v)
    {
        echo "<tr>" ;
        echo "<td>" .$v->getMenuNumber(). "</td>" ;
        echo "<td>" .$v->getDescription() . "</td>" ;
        echo "</tr>" ;
    }
?>
</table>
<?php
}
?>



<h3>Items already served</h3>

<?php
if(count($result->getItemsServed()) == 0)
{
    echo 'Pas de commande en cours' ;
} else {
?>
<table>
    <tr>
        <th>Menu #</th>
        <th>Description</th>
    </tr>
<?php    
    foreach($result->getItemsServed() as $k=> $v)
    {
        echo "<tr>" ;
        echo "<td>" .$v->getMenuNumber(). "</td>" ;
        echo "<td>" .$v->getDescription() . "</td>" ;
        echo "</tr>" ;
    }
?>
</table>
<?php
}
?>
