<h1>Ouvrir une nouvelle note</h1>

<?php 
$form = $this->result['form'] ;
$form->prepare() ;

// l’action va nous renvoyer sur la route ‘tab/open’ 
// soit TabController / OpenAction tel que défini dans la route dans module.config.php
$form->setAttribute('action',  $this->url('tab/open')) ;
$form->setAttribute('method', 'post') ;

// on génère l'id unique dans la vue
$id = $form->get('id') ;
$id->setValue(uniqid()) ;

?>

<?php  echo $this->form()->openTag($form) ; ?>
<div class='form-group'>
<?php  echo $this->formRow($form->get('tableNumber')) ; ?>
</div>
<div class='form-group'>
<?php  echo $this->formRow($form->get('waiter')) ; ?>
</div>
<?php
echo $this->formRow($form->get('security')) ;
echo $this->formHidden($id) ;
echo $this->formRow($form->get('submit')) ;

echo $this->form()->closeTag() ;
?>

