 <script>
     function add_item() {
         var currentCount = $('form fieldset fieldset').length;
         var template = $('form fieldset > span').data('template');
         template = template.replace(/__index__/g, currentCount);
         $('form fieldset').last().append(template);

         return false;
     }
 </script>

<h1>Passer commande</h1>

<?php 
$form = $this->result['form'] ;
$form->prepare() ;

$form->setAttribute('action',  $this->url('tab/order')) ;
$form->setAttribute('method', 'post') ;

?>

<?php  echo $this->form()->openTag($form) ; ?>
<div class='form-group'>
<?php  echo $this->formRow($form->get('id')) ; ?>
</div>
<div class='form-group'>
    <fieldset>
        <legend><?php $this->formLabel($form->get('items')) ; ?></legend>
<?php
    foreach($form->get('items')->getIterator() as $fieldset)
    {
        echo '<fieldset class="form-inline">' ;
        echo $this->formRow($fieldset->get('id')). '&nbsp;&nbsp;' ;
        echo $this->formRow($fieldset->get('number')) ;
        echo '</fieldset>' ;
    }
    // et voici notre aide de vue
    echo $this->MenuItemFormCollection()->renderTemplate($form->get('items'));
?>
    </fieldset>
<button onclick="return add_item()">Add a new item</button>
</div>
    <?php
echo $this->formRow($form->get('security')) ;
echo $this->formRow($form->get('submit')) ;
echo $this->form()->closeTag() ;
?>
