<h2>Meals to prepare</h2>

<form action='<?php echo $this->url('chef/markprepared') ; ?>' method='post'>
<?php
foreach($result as $group)
{
    $i = 0 ;
?>
    <input type='hidden' value='<?php echo $group->getTab() ; ?>' name='id'/>
    <table>
        <tr>
            <th>Menu #</th>
            <th>Description</th>
            <th>Prepared</th>
        </tr>
        <?php
        foreach($group->getItems() as $item)
        {
        ?>
            <tr>
            <td><?php echo $item->getMenuNumber() ; ?></td>
            <td><?php echo $item->getDescription() ; ?></td>
            <td><input type='checkbox' name='prepared[]' value='prepared_<?php echo $i++ ; ?>_<?php echo $item->getMenuNumber() ; ?>'/></td>
            </tr>
        <?php
        }
        ?>
    </table>
    
    <input type='submit' name='submit' value='Mark Prepared'/>
<?php
}
?>
</form>
